version=3.0.0
server.one.local.host=127.0.0.1
server.one.client.port=50201
server.one.broker.port=50301
server.one.heartbeat.port=50501
monitor.heartbeat.server.host=127.0.0.1
monitor.heartbeat.server.port=49001
monitor.address.server.host=127.0.0.1
monitor.address.server.port=49002
monitor.heartbeat.interval=1000
