version=4.0.0
EncryptionStrategy=AES
server.one.local.host=127.0.0.1
server.one.client.port=50201
server.one.broker.port=50301
server.one.heartbeat.port=50501
server.two.local.host=127.0.0.1
server.two.client.port=50202
server.two.broker.port=50302
server.two.heartbeat.port=50502
server.three.local.host=127.0.0.1
server.three.client.port=50203
server.three.broker.port=50303
server.three.heartbeat.port=50503
server.heartbeat.rate=250
monitor.heartbeat.server.host=127.0.0.1
monitor.heartbeat.server.port=49001
monitor.address.server.host=127.0.0.1
monitor.address.server.port=49002
monitor.heartbeat.tolerance=500
broker.server.host=127.0.0.1
broker.server.port=55001